version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doc_management
      - JWT_SECRET_KEY=your_secret_key
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=False
      - MINIO_BUCKET_NAME=documents
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - db
      - minio
      - chroma

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=doc_management
    restart: always
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    restart: always

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_CORS_ORIGINS=["*"]
    ports:
      - "8001:8000"
    restart: always


volumes:
  postgres_data:
  minio_data:
  chroma_data: